//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.paxfacturacion.com.mx:453", ConfigurationName="wsTimbradoASPEL.wcfRecepcionASPELSoap")]
    public interface wcfRecepcionASPELSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento psComprobante del espacio de nombres https://www.paxfacturacion.com.mx:453 no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paxfacturacion.com.mx:453/fnEnviarXML", ReplyAction="*")]
        SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.fnEnviarXMLResponse fnEnviarXML(SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.fnEnviarXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnEnviarXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnEnviarXML", Namespace="https://www.paxfacturacion.com.mx:453", Order=0)]
        public SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.fnEnviarXMLRequestBody Body;
        
        public fnEnviarXMLRequest() {
        }
        
        public fnEnviarXMLRequest(SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.fnEnviarXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.paxfacturacion.com.mx:453")]
    public partial class fnEnviarXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string psComprobante;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psTipoDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pnId_Estructura;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sContrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sVersion;
        
        public fnEnviarXMLRequestBody() {
        }
        
        public fnEnviarXMLRequestBody(string psComprobante, string psTipoDocumento, int pnId_Estructura, string sNombre, string sContrasena, string sVersion) {
            this.psComprobante = psComprobante;
            this.psTipoDocumento = psTipoDocumento;
            this.pnId_Estructura = pnId_Estructura;
            this.sNombre = sNombre;
            this.sContrasena = sContrasena;
            this.sVersion = sVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnEnviarXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnEnviarXMLResponse", Namespace="https://www.paxfacturacion.com.mx:453", Order=0)]
        public SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.fnEnviarXMLResponseBody Body;
        
        public fnEnviarXMLResponse() {
        }
        
        public fnEnviarXMLResponse(SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.fnEnviarXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.paxfacturacion.com.mx:453")]
    public partial class fnEnviarXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fnEnviarXMLResult;
        
        public fnEnviarXMLResponseBody() {
        }
        
        public fnEnviarXMLResponseBody(string fnEnviarXMLResult) {
            this.fnEnviarXMLResult = fnEnviarXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wcfRecepcionASPELSoapChannel : SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.wcfRecepcionASPELSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wcfRecepcionASPELSoapClient : System.ServiceModel.ClientBase<SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.wcfRecepcionASPELSoap>, SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.wcfRecepcionASPELSoap {
        
        public wcfRecepcionASPELSoapClient() {
        }
        
        public wcfRecepcionASPELSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wcfRecepcionASPELSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wcfRecepcionASPELSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wcfRecepcionASPELSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.fnEnviarXMLResponse SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.wcfRecepcionASPELSoap.fnEnviarXML(SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.fnEnviarXMLRequest request) {
            return base.Channel.fnEnviarXML(request);
        }
        
        public string fnEnviarXML(string psComprobante, string psTipoDocumento, int pnId_Estructura, string sNombre, string sContrasena, string sVersion) {
            SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.fnEnviarXMLRequest inValue = new SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.fnEnviarXMLRequest();
            inValue.Body = new SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.fnEnviarXMLRequestBody();
            inValue.Body.psComprobante = psComprobante;
            inValue.Body.psTipoDocumento = psTipoDocumento;
            inValue.Body.pnId_Estructura = pnId_Estructura;
            inValue.Body.sNombre = sNombre;
            inValue.Body.sContrasena = sContrasena;
            inValue.Body.sVersion = sVersion;
            SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.fnEnviarXMLResponse retVal = ((SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoASPEL.wcfRecepcionASPELSoap)(this)).fnEnviarXML(inValue);
            return retVal.Body.fnEnviarXMLResult;
        }
    }
}
