//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebServiceRetenciones.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan.Hernandez\\Desktop\\Layouts\\Layouts Retenciones\\Salida")]
        public string Salida {
            get {
                return ((string)(this["Salida"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan.Hernandez\\Desktop\\SAT CLIENTE Sistema Pruebas 3.2\\Ejemplos_SAT\\Logs" +
            "")]
        public string Logs {
            get {
                return ((string)(this["Logs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan.Hernandez\\Desktop\\SAT CLIENTE Sistema Pruebas 3.2\\Ejemplos_SAT\\Guar" +
            "dar Acuse")]
        public string Acuses {
            get {
                return ((string)(this["Acuses"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan.Hernandez\\Desktop\\SAT CLIENTE Sistema Pruebas 3.2\\Ejemplos_SAT\\Move" +
            "r CFDI")]
        public string CFDI {
            get {
                return ((string)(this["CFDI"]));
            }
        }
    }
}
