//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://www.paxfacturacion.mx:455", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.paxfacturacion.mx:455", ConfigurationName="wsRegistroUsuariosTestN.wcfRegistroSoap")]
    public interface wcfRegistroSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sNombreUsuario del espacio de nombres https://www.paxfacturacion.mx:455 no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://www.paxfacturacion.mx:455/fnRegistraUsuario", ReplyAction="*")]
        SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.fnRegistraUsuarioResponse fnRegistraUsuario(SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.fnRegistraUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnRegistraUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnRegistraUsuario", Namespace="https://www.paxfacturacion.mx:455", Order=0)]
        public SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.fnRegistraUsuarioRequestBody Body;
        
        public fnRegistraUsuarioRequest() {
        }
        
        public fnRegistraUsuarioRequest(SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.fnRegistraUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.paxfacturacion.mx:455")]
    public partial class fnRegistraUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sNombreUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sContraseñaUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.ArrayOfString sDatos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sNombreCertificado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] btCertificado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sContraseñaCert;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sNombreLlavePriv;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public byte[] btLLavePrivada;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string sUsuarioHijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sContraseñaUsuarioHijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string sEmailUsuHijo;
        
        public fnRegistraUsuarioRequestBody() {
        }
        
        public fnRegistraUsuarioRequestBody(string sNombreUsuario, string sContraseñaUsuario, SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.ArrayOfString sDatos, string sNombreCertificado, byte[] btCertificado, string sContraseñaCert, string sNombreLlavePriv, byte[] btLLavePrivada, string sUsuarioHijo, string sContraseñaUsuarioHijo, string sEmailUsuHijo) {
            this.sNombreUsuario = sNombreUsuario;
            this.sContraseñaUsuario = sContraseñaUsuario;
            this.sDatos = sDatos;
            this.sNombreCertificado = sNombreCertificado;
            this.btCertificado = btCertificado;
            this.sContraseñaCert = sContraseñaCert;
            this.sNombreLlavePriv = sNombreLlavePriv;
            this.btLLavePrivada = btLLavePrivada;
            this.sUsuarioHijo = sUsuarioHijo;
            this.sContraseñaUsuarioHijo = sContraseñaUsuarioHijo;
            this.sEmailUsuHijo = sEmailUsuHijo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnRegistraUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnRegistraUsuarioResponse", Namespace="https://www.paxfacturacion.mx:455", Order=0)]
        public SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.fnRegistraUsuarioResponseBody Body;
        
        public fnRegistraUsuarioResponse() {
        }
        
        public fnRegistraUsuarioResponse(SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.fnRegistraUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.paxfacturacion.mx:455")]
    public partial class fnRegistraUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fnRegistraUsuarioResult;
        
        public fnRegistraUsuarioResponseBody() {
        }
        
        public fnRegistraUsuarioResponseBody(string fnRegistraUsuarioResult) {
            this.fnRegistraUsuarioResult = fnRegistraUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wcfRegistroSoapChannel : SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.wcfRegistroSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wcfRegistroSoapClient : System.ServiceModel.ClientBase<SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.wcfRegistroSoap>, SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.wcfRegistroSoap {
        
        public wcfRegistroSoapClient() {
        }
        
        public wcfRegistroSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wcfRegistroSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wcfRegistroSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wcfRegistroSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.fnRegistraUsuarioResponse SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.wcfRegistroSoap.fnRegistraUsuario(SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.fnRegistraUsuarioRequest request) {
            return base.Channel.fnRegistraUsuario(request);
        }
        
        public string fnRegistraUsuario(string sNombreUsuario, string sContraseñaUsuario, SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.ArrayOfString sDatos, string sNombreCertificado, byte[] btCertificado, string sContraseñaCert, string sNombreLlavePriv, byte[] btLLavePrivada, string sUsuarioHijo, string sContraseñaUsuarioHijo, string sEmailUsuHijo) {
            SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.fnRegistraUsuarioRequest inValue = new SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.fnRegistraUsuarioRequest();
            inValue.Body = new SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.fnRegistraUsuarioRequestBody();
            inValue.Body.sNombreUsuario = sNombreUsuario;
            inValue.Body.sContraseñaUsuario = sContraseñaUsuario;
            inValue.Body.sDatos = sDatos;
            inValue.Body.sNombreCertificado = sNombreCertificado;
            inValue.Body.btCertificado = btCertificado;
            inValue.Body.sContraseñaCert = sContraseñaCert;
            inValue.Body.sNombreLlavePriv = sNombreLlavePriv;
            inValue.Body.btLLavePrivada = btLLavePrivada;
            inValue.Body.sUsuarioHijo = sUsuarioHijo;
            inValue.Body.sContraseñaUsuarioHijo = sContraseñaUsuarioHijo;
            inValue.Body.sEmailUsuHijo = sEmailUsuHijo;
            SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.fnRegistraUsuarioResponse retVal = ((SolucionPruebas.Presentacion.Servicios.wsRegistroUsuariosTestN.wcfRegistroSoap)(this)).fnRegistraUsuario(inValue);
            return retVal.Body.fnRegistraUsuarioResult;
        }
    }
}
