//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
// 
#pragma warning disable 1591

namespace SolucionPruebas.Presentacion.TimbradoIBM.wsTimbradoSVC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'PolicyReference' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IwcfRecepcion", Namespace="https://www.paxfacturacion.com.mx:453")]
    public partial class wcfRecepcion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback fnEnviarXMLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wcfRecepcion() {
            this.Url = global::SolucionPruebas.Presentacion.TimbradoIBM.Properties.Settings.Default.SolucionPruebas_Presentacion_TimbradoIBM_wsTimbradoSVC_wcfRecepcion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event fnEnviarXMLCompletedEventHandler fnEnviarXMLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.paxfacturacion.com.mx:453/IwcfRecepcion/fnEnviarXML", RequestNamespace="https://www.paxfacturacion.com.mx:453", ResponseNamespace="https://www.paxfacturacion.com.mx:453", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fnEnviarXML([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string psComprobante, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string psTipoDocumento, int pnId_Estructura, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pnId_EstructuraSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sNombre, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sContraseña, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sVersion) {
            object[] results = this.Invoke("fnEnviarXML", new object[] {
                        psComprobante,
                        psTipoDocumento,
                        pnId_Estructura,
                        pnId_EstructuraSpecified,
                        sNombre,
                        sContraseña,
                        sVersion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fnEnviarXMLAsync(string psComprobante, string psTipoDocumento, int pnId_Estructura, bool pnId_EstructuraSpecified, string sNombre, string sContraseña, string sVersion) {
            this.fnEnviarXMLAsync(psComprobante, psTipoDocumento, pnId_Estructura, pnId_EstructuraSpecified, sNombre, sContraseña, sVersion, null);
        }
        
        /// <remarks/>
        public void fnEnviarXMLAsync(string psComprobante, string psTipoDocumento, int pnId_Estructura, bool pnId_EstructuraSpecified, string sNombre, string sContraseña, string sVersion, object userState) {
            if ((this.fnEnviarXMLOperationCompleted == null)) {
                this.fnEnviarXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnEnviarXMLOperationCompleted);
            }
            this.InvokeAsync("fnEnviarXML", new object[] {
                        psComprobante,
                        psTipoDocumento,
                        pnId_Estructura,
                        pnId_EstructuraSpecified,
                        sNombre,
                        sContraseña,
                        sVersion}, this.fnEnviarXMLOperationCompleted, userState);
        }
        
        private void OnfnEnviarXMLOperationCompleted(object arg) {
            if ((this.fnEnviarXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnEnviarXMLCompleted(this, new fnEnviarXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void fnEnviarXMLCompletedEventHandler(object sender, fnEnviarXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnEnviarXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnEnviarXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591