//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18449.
// 
#pragma warning disable 1591

namespace P_PruebasConammConsumoWSAutentica.wsPAXAutentificaConamm {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PAXAutentificaConammSoap", Namespace="http://paxfacturacion.com/")]
    public partial class PAXAutentificaConamm : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback fnEmpleadoExisteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PAXAutentificaConamm() {
            this.Url = global::P_PruebasConammConsumoWSAutentica.Properties.Settings.Default.P_PruebasConammConsumoWSAutentica_wsPAXAutentificaConamm_PAXAutentificaConamm;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event fnEmpleadoExisteCompletedEventHandler fnEmpleadoExisteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://paxfacturacion.com/fnEmpleadoExiste", RequestNamespace="http://paxfacturacion.com/", ResponseNamespace="http://paxfacturacion.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool fnEmpleadoExiste(string pstrNumEmpleado, string pstrRFC, string pstrsCURP, string psClaveOrganismo, string psUsuario, string psContraseña) {
            object[] results = this.Invoke("fnEmpleadoExiste", new object[] {
                        pstrNumEmpleado,
                        pstrRFC,
                        pstrsCURP,
                        psClaveOrganismo,
                        psUsuario,
                        psContraseña});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void fnEmpleadoExisteAsync(string pstrNumEmpleado, string pstrRFC, string pstrsCURP, string psClaveOrganismo, string psUsuario, string psContraseña) {
            this.fnEmpleadoExisteAsync(pstrNumEmpleado, pstrRFC, pstrsCURP, psClaveOrganismo, psUsuario, psContraseña, null);
        }
        
        /// <remarks/>
        public void fnEmpleadoExisteAsync(string pstrNumEmpleado, string pstrRFC, string pstrsCURP, string psClaveOrganismo, string psUsuario, string psContraseña, object userState) {
            if ((this.fnEmpleadoExisteOperationCompleted == null)) {
                this.fnEmpleadoExisteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnEmpleadoExisteOperationCompleted);
            }
            this.InvokeAsync("fnEmpleadoExiste", new object[] {
                        pstrNumEmpleado,
                        pstrRFC,
                        pstrsCURP,
                        psClaveOrganismo,
                        psUsuario,
                        psContraseña}, this.fnEmpleadoExisteOperationCompleted, userState);
        }
        
        private void OnfnEmpleadoExisteOperationCompleted(object arg) {
            if ((this.fnEmpleadoExisteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnEmpleadoExisteCompleted(this, new fnEmpleadoExisteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void fnEmpleadoExisteCompletedEventHandler(object sender, fnEmpleadoExisteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnEmpleadoExisteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnEmpleadoExisteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591