//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.Cancel {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://test.paxfacturacion.com.mx:476", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://test.paxfacturacion.com.mx:476", ConfigurationName="Cancel.wcfCancelaASMXSoap")]
    public interface wcfCancelaASMXSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sListaUUID del espacio de nombres https://test.paxfacturacion.com.mx:476 no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://test.paxfacturacion.com.mx:476/fnCancelarXML", ReplyAction="*")]
        ConsoleApplication1.Cancel.fnCancelarXMLResponse fnCancelarXML(ConsoleApplication1.Cancel.fnCancelarXMLRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sListaUUID del espacio de nombres https://test.paxfacturacion.com.mx:476 no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://test.paxfacturacion.com.mx:476/fnCancelarDistribuidoresXML", ReplyAction="*")]
        ConsoleApplication1.Cancel.fnCancelarDistribuidoresXMLResponse fnCancelarDistribuidoresXML(ConsoleApplication1.Cancel.fnCancelarDistribuidoresXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnCancelarXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnCancelarXML", Namespace="https://test.paxfacturacion.com.mx:476", Order=0)]
        public ConsoleApplication1.Cancel.fnCancelarXMLRequestBody Body;
        
        public fnCancelarXMLRequest() {
        }
        
        public fnCancelarXMLRequest(ConsoleApplication1.Cancel.fnCancelarXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.paxfacturacion.com.mx:476")]
    public partial class fnCancelarXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.Cancel.ArrayOfString sListaUUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psRFCEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ConsoleApplication1.Cancel.ArrayOfString psRFCReceptor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ConsoleApplication1.Cancel.ArrayOfString sListaTotales;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sContrasena;
        
        public fnCancelarXMLRequestBody() {
        }
        
        public fnCancelarXMLRequestBody(ConsoleApplication1.Cancel.ArrayOfString sListaUUID, string psRFCEmisor, ConsoleApplication1.Cancel.ArrayOfString psRFCReceptor, ConsoleApplication1.Cancel.ArrayOfString sListaTotales, string sNombre, string sContrasena) {
            this.sListaUUID = sListaUUID;
            this.psRFCEmisor = psRFCEmisor;
            this.psRFCReceptor = psRFCReceptor;
            this.sListaTotales = sListaTotales;
            this.sNombre = sNombre;
            this.sContrasena = sContrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnCancelarXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnCancelarXMLResponse", Namespace="https://test.paxfacturacion.com.mx:476", Order=0)]
        public ConsoleApplication1.Cancel.fnCancelarXMLResponseBody Body;
        
        public fnCancelarXMLResponse() {
        }
        
        public fnCancelarXMLResponse(ConsoleApplication1.Cancel.fnCancelarXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.paxfacturacion.com.mx:476")]
    public partial class fnCancelarXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fnCancelarXMLResult;
        
        public fnCancelarXMLResponseBody() {
        }
        
        public fnCancelarXMLResponseBody(string fnCancelarXMLResult) {
            this.fnCancelarXMLResult = fnCancelarXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnCancelarDistribuidoresXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnCancelarDistribuidoresXML", Namespace="https://test.paxfacturacion.com.mx:476", Order=0)]
        public ConsoleApplication1.Cancel.fnCancelarDistribuidoresXMLRequestBody Body;
        
        public fnCancelarDistribuidoresXMLRequest() {
        }
        
        public fnCancelarDistribuidoresXMLRequest(ConsoleApplication1.Cancel.fnCancelarDistribuidoresXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.paxfacturacion.com.mx:476")]
    public partial class fnCancelarDistribuidoresXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.Cancel.ArrayOfString sListaUUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psRFCEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ConsoleApplication1.Cancel.ArrayOfString psRFCReceptor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ConsoleApplication1.Cancel.ArrayOfString sListaTotales;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sContrasena;
        
        public fnCancelarDistribuidoresXMLRequestBody() {
        }
        
        public fnCancelarDistribuidoresXMLRequestBody(ConsoleApplication1.Cancel.ArrayOfString sListaUUID, string psRFCEmisor, ConsoleApplication1.Cancel.ArrayOfString psRFCReceptor, ConsoleApplication1.Cancel.ArrayOfString sListaTotales, string signature, string sNombre, string sContrasena) {
            this.sListaUUID = sListaUUID;
            this.psRFCEmisor = psRFCEmisor;
            this.psRFCReceptor = psRFCReceptor;
            this.sListaTotales = sListaTotales;
            this.signature = signature;
            this.sNombre = sNombre;
            this.sContrasena = sContrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnCancelarDistribuidoresXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnCancelarDistribuidoresXMLResponse", Namespace="https://test.paxfacturacion.com.mx:476", Order=0)]
        public ConsoleApplication1.Cancel.fnCancelarDistribuidoresXMLResponseBody Body;
        
        public fnCancelarDistribuidoresXMLResponse() {
        }
        
        public fnCancelarDistribuidoresXMLResponse(ConsoleApplication1.Cancel.fnCancelarDistribuidoresXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.paxfacturacion.com.mx:476")]
    public partial class fnCancelarDistribuidoresXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fnCancelarDistribuidoresXMLResult;
        
        public fnCancelarDistribuidoresXMLResponseBody() {
        }
        
        public fnCancelarDistribuidoresXMLResponseBody(string fnCancelarDistribuidoresXMLResult) {
            this.fnCancelarDistribuidoresXMLResult = fnCancelarDistribuidoresXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wcfCancelaASMXSoapChannel : ConsoleApplication1.Cancel.wcfCancelaASMXSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wcfCancelaASMXSoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.Cancel.wcfCancelaASMXSoap>, ConsoleApplication1.Cancel.wcfCancelaASMXSoap {
        
        public wcfCancelaASMXSoapClient() {
        }
        
        public wcfCancelaASMXSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wcfCancelaASMXSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wcfCancelaASMXSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wcfCancelaASMXSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.Cancel.fnCancelarXMLResponse ConsoleApplication1.Cancel.wcfCancelaASMXSoap.fnCancelarXML(ConsoleApplication1.Cancel.fnCancelarXMLRequest request) {
            return base.Channel.fnCancelarXML(request);
        }
        
        public string fnCancelarXML(ConsoleApplication1.Cancel.ArrayOfString sListaUUID, string psRFCEmisor, ConsoleApplication1.Cancel.ArrayOfString psRFCReceptor, ConsoleApplication1.Cancel.ArrayOfString sListaTotales, string sNombre, string sContrasena) {
            ConsoleApplication1.Cancel.fnCancelarXMLRequest inValue = new ConsoleApplication1.Cancel.fnCancelarXMLRequest();
            inValue.Body = new ConsoleApplication1.Cancel.fnCancelarXMLRequestBody();
            inValue.Body.sListaUUID = sListaUUID;
            inValue.Body.psRFCEmisor = psRFCEmisor;
            inValue.Body.psRFCReceptor = psRFCReceptor;
            inValue.Body.sListaTotales = sListaTotales;
            inValue.Body.sNombre = sNombre;
            inValue.Body.sContrasena = sContrasena;
            ConsoleApplication1.Cancel.fnCancelarXMLResponse retVal = ((ConsoleApplication1.Cancel.wcfCancelaASMXSoap)(this)).fnCancelarXML(inValue);
            return retVal.Body.fnCancelarXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.Cancel.fnCancelarDistribuidoresXMLResponse ConsoleApplication1.Cancel.wcfCancelaASMXSoap.fnCancelarDistribuidoresXML(ConsoleApplication1.Cancel.fnCancelarDistribuidoresXMLRequest request) {
            return base.Channel.fnCancelarDistribuidoresXML(request);
        }
        
        public string fnCancelarDistribuidoresXML(ConsoleApplication1.Cancel.ArrayOfString sListaUUID, string psRFCEmisor, ConsoleApplication1.Cancel.ArrayOfString psRFCReceptor, ConsoleApplication1.Cancel.ArrayOfString sListaTotales, string signature, string sNombre, string sContrasena) {
            ConsoleApplication1.Cancel.fnCancelarDistribuidoresXMLRequest inValue = new ConsoleApplication1.Cancel.fnCancelarDistribuidoresXMLRequest();
            inValue.Body = new ConsoleApplication1.Cancel.fnCancelarDistribuidoresXMLRequestBody();
            inValue.Body.sListaUUID = sListaUUID;
            inValue.Body.psRFCEmisor = psRFCEmisor;
            inValue.Body.psRFCReceptor = psRFCReceptor;
            inValue.Body.sListaTotales = sListaTotales;
            inValue.Body.signature = signature;
            inValue.Body.sNombre = sNombre;
            inValue.Body.sContrasena = sContrasena;
            ConsoleApplication1.Cancel.fnCancelarDistribuidoresXMLResponse retVal = ((ConsoleApplication1.Cancel.wcfCancelaASMXSoap)(this)).fnCancelarDistribuidoresXML(inValue);
            return retVal.Body.fnCancelarDistribuidoresXMLResult;
        }
    }
}
