//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAXConectorCapacitacion06.wsCancela {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://test.paxfacturacion.com.mx:476", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://test.paxfacturacion.com.mx:476", ConfigurationName="wsCancela.wcfCancelaASMXSoap")]
    public interface wcfCancelaASMXSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sListaUUID del espacio de nombres https://test.paxfacturacion.com.mx:476 no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://test.paxfacturacion.com.mx:476/fnCancelarXML", ReplyAction="*")]
        PAXConectorCapacitacion06.wsCancela.fnCancelarXMLResponse fnCancelarXML(PAXConectorCapacitacion06.wsCancela.fnCancelarXMLRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sListaUUID del espacio de nombres https://test.paxfacturacion.com.mx:476 no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://test.paxfacturacion.com.mx:476/fnCancelarDistribuidoresXML", ReplyAction="*")]
        PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLResponse fnCancelarDistribuidoresXML(PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sListaUUID del espacio de nombres https://test.paxfacturacion.com.mx:476 no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://test.paxfacturacion.com.mx:476/fnCancelarXMLMP", ReplyAction="*")]
        PAXConectorCapacitacion06.wsCancela.fnCancelarXMLMPResponse fnCancelarXMLMP(PAXConectorCapacitacion06.wsCancela.fnCancelarXMLMPRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sListaUUID del espacio de nombres https://test.paxfacturacion.com.mx:476 no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://test.paxfacturacion.com.mx:476/fnCancelarDistribuidoresXMLMP", ReplyAction="*")]
        PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLMPResponse fnCancelarDistribuidoresXMLMP(PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLMPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnCancelarXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnCancelarXML", Namespace="https://test.paxfacturacion.com.mx:476", Order=0)]
        public PAXConectorCapacitacion06.wsCancela.fnCancelarXMLRequestBody Body;
        
        public fnCancelarXMLRequest() {
        }
        
        public fnCancelarXMLRequest(PAXConectorCapacitacion06.wsCancela.fnCancelarXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.paxfacturacion.com.mx:476")]
    public partial class fnCancelarXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaUUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psRFCEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public PAXConectorCapacitacion06.wsCancela.ArrayOfString psRFCReceptor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaTotales;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sContrasena;
        
        public fnCancelarXMLRequestBody() {
        }
        
        public fnCancelarXMLRequestBody(PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaUUID, string psRFCEmisor, PAXConectorCapacitacion06.wsCancela.ArrayOfString psRFCReceptor, PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaTotales, string sNombre, string sContrasena) {
            this.sListaUUID = sListaUUID;
            this.psRFCEmisor = psRFCEmisor;
            this.psRFCReceptor = psRFCReceptor;
            this.sListaTotales = sListaTotales;
            this.sNombre = sNombre;
            this.sContrasena = sContrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnCancelarXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnCancelarXMLResponse", Namespace="https://test.paxfacturacion.com.mx:476", Order=0)]
        public PAXConectorCapacitacion06.wsCancela.fnCancelarXMLResponseBody Body;
        
        public fnCancelarXMLResponse() {
        }
        
        public fnCancelarXMLResponse(PAXConectorCapacitacion06.wsCancela.fnCancelarXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.paxfacturacion.com.mx:476")]
    public partial class fnCancelarXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fnCancelarXMLResult;
        
        public fnCancelarXMLResponseBody() {
        }
        
        public fnCancelarXMLResponseBody(string fnCancelarXMLResult) {
            this.fnCancelarXMLResult = fnCancelarXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnCancelarDistribuidoresXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnCancelarDistribuidoresXML", Namespace="https://test.paxfacturacion.com.mx:476", Order=0)]
        public PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLRequestBody Body;
        
        public fnCancelarDistribuidoresXMLRequest() {
        }
        
        public fnCancelarDistribuidoresXMLRequest(PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.paxfacturacion.com.mx:476")]
    public partial class fnCancelarDistribuidoresXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaUUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psRFCEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public PAXConectorCapacitacion06.wsCancela.ArrayOfString psRFCReceptor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaTotales;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sContrasena;
        
        public fnCancelarDistribuidoresXMLRequestBody() {
        }
        
        public fnCancelarDistribuidoresXMLRequestBody(PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaUUID, string psRFCEmisor, PAXConectorCapacitacion06.wsCancela.ArrayOfString psRFCReceptor, PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaTotales, string signature, string sNombre, string sContrasena) {
            this.sListaUUID = sListaUUID;
            this.psRFCEmisor = psRFCEmisor;
            this.psRFCReceptor = psRFCReceptor;
            this.sListaTotales = sListaTotales;
            this.signature = signature;
            this.sNombre = sNombre;
            this.sContrasena = sContrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnCancelarDistribuidoresXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnCancelarDistribuidoresXMLResponse", Namespace="https://test.paxfacturacion.com.mx:476", Order=0)]
        public PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLResponseBody Body;
        
        public fnCancelarDistribuidoresXMLResponse() {
        }
        
        public fnCancelarDistribuidoresXMLResponse(PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.paxfacturacion.com.mx:476")]
    public partial class fnCancelarDistribuidoresXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fnCancelarDistribuidoresXMLResult;
        
        public fnCancelarDistribuidoresXMLResponseBody() {
        }
        
        public fnCancelarDistribuidoresXMLResponseBody(string fnCancelarDistribuidoresXMLResult) {
            this.fnCancelarDistribuidoresXMLResult = fnCancelarDistribuidoresXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnCancelarXMLMPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnCancelarXMLMP", Namespace="https://test.paxfacturacion.com.mx:476", Order=0)]
        public PAXConectorCapacitacion06.wsCancela.fnCancelarXMLMPRequestBody Body;
        
        public fnCancelarXMLMPRequest() {
        }
        
        public fnCancelarXMLMPRequest(PAXConectorCapacitacion06.wsCancela.fnCancelarXMLMPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.paxfacturacion.com.mx:476")]
    public partial class fnCancelarXMLMPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaUUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psRFCEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sContrasena;
        
        public fnCancelarXMLMPRequestBody() {
        }
        
        public fnCancelarXMLMPRequestBody(PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaUUID, string psRFCEmisor, string sNombre, string sContrasena) {
            this.sListaUUID = sListaUUID;
            this.psRFCEmisor = psRFCEmisor;
            this.sNombre = sNombre;
            this.sContrasena = sContrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnCancelarXMLMPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnCancelarXMLMPResponse", Namespace="https://test.paxfacturacion.com.mx:476", Order=0)]
        public PAXConectorCapacitacion06.wsCancela.fnCancelarXMLMPResponseBody Body;
        
        public fnCancelarXMLMPResponse() {
        }
        
        public fnCancelarXMLMPResponse(PAXConectorCapacitacion06.wsCancela.fnCancelarXMLMPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.paxfacturacion.com.mx:476")]
    public partial class fnCancelarXMLMPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fnCancelarXMLMPResult;
        
        public fnCancelarXMLMPResponseBody() {
        }
        
        public fnCancelarXMLMPResponseBody(string fnCancelarXMLMPResult) {
            this.fnCancelarXMLMPResult = fnCancelarXMLMPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnCancelarDistribuidoresXMLMPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnCancelarDistribuidoresXMLMP", Namespace="https://test.paxfacturacion.com.mx:476", Order=0)]
        public PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLMPRequestBody Body;
        
        public fnCancelarDistribuidoresXMLMPRequest() {
        }
        
        public fnCancelarDistribuidoresXMLMPRequest(PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLMPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.paxfacturacion.com.mx:476")]
    public partial class fnCancelarDistribuidoresXMLMPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaUUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string psRFCEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sContrasena;
        
        public fnCancelarDistribuidoresXMLMPRequestBody() {
        }
        
        public fnCancelarDistribuidoresXMLMPRequestBody(PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaUUID, string psRFCEmisor, string signature, string sNombre, string sContrasena) {
            this.sListaUUID = sListaUUID;
            this.psRFCEmisor = psRFCEmisor;
            this.signature = signature;
            this.sNombre = sNombre;
            this.sContrasena = sContrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fnCancelarDistribuidoresXMLMPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fnCancelarDistribuidoresXMLMPResponse", Namespace="https://test.paxfacturacion.com.mx:476", Order=0)]
        public PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLMPResponseBody Body;
        
        public fnCancelarDistribuidoresXMLMPResponse() {
        }
        
        public fnCancelarDistribuidoresXMLMPResponse(PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLMPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.paxfacturacion.com.mx:476")]
    public partial class fnCancelarDistribuidoresXMLMPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fnCancelarDistribuidoresXMLMPResult;
        
        public fnCancelarDistribuidoresXMLMPResponseBody() {
        }
        
        public fnCancelarDistribuidoresXMLMPResponseBody(string fnCancelarDistribuidoresXMLMPResult) {
            this.fnCancelarDistribuidoresXMLMPResult = fnCancelarDistribuidoresXMLMPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wcfCancelaASMXSoapChannel : PAXConectorCapacitacion06.wsCancela.wcfCancelaASMXSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wcfCancelaASMXSoapClient : System.ServiceModel.ClientBase<PAXConectorCapacitacion06.wsCancela.wcfCancelaASMXSoap>, PAXConectorCapacitacion06.wsCancela.wcfCancelaASMXSoap {
        
        public wcfCancelaASMXSoapClient() {
        }
        
        public wcfCancelaASMXSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wcfCancelaASMXSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wcfCancelaASMXSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wcfCancelaASMXSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PAXConectorCapacitacion06.wsCancela.fnCancelarXMLResponse PAXConectorCapacitacion06.wsCancela.wcfCancelaASMXSoap.fnCancelarXML(PAXConectorCapacitacion06.wsCancela.fnCancelarXMLRequest request) {
            return base.Channel.fnCancelarXML(request);
        }
        
        public string fnCancelarXML(PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaUUID, string psRFCEmisor, PAXConectorCapacitacion06.wsCancela.ArrayOfString psRFCReceptor, PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaTotales, string sNombre, string sContrasena) {
            PAXConectorCapacitacion06.wsCancela.fnCancelarXMLRequest inValue = new PAXConectorCapacitacion06.wsCancela.fnCancelarXMLRequest();
            inValue.Body = new PAXConectorCapacitacion06.wsCancela.fnCancelarXMLRequestBody();
            inValue.Body.sListaUUID = sListaUUID;
            inValue.Body.psRFCEmisor = psRFCEmisor;
            inValue.Body.psRFCReceptor = psRFCReceptor;
            inValue.Body.sListaTotales = sListaTotales;
            inValue.Body.sNombre = sNombre;
            inValue.Body.sContrasena = sContrasena;
            PAXConectorCapacitacion06.wsCancela.fnCancelarXMLResponse retVal = ((PAXConectorCapacitacion06.wsCancela.wcfCancelaASMXSoap)(this)).fnCancelarXML(inValue);
            return retVal.Body.fnCancelarXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLResponse PAXConectorCapacitacion06.wsCancela.wcfCancelaASMXSoap.fnCancelarDistribuidoresXML(PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLRequest request) {
            return base.Channel.fnCancelarDistribuidoresXML(request);
        }
        
        public string fnCancelarDistribuidoresXML(PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaUUID, string psRFCEmisor, PAXConectorCapacitacion06.wsCancela.ArrayOfString psRFCReceptor, PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaTotales, string signature, string sNombre, string sContrasena) {
            PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLRequest inValue = new PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLRequest();
            inValue.Body = new PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLRequestBody();
            inValue.Body.sListaUUID = sListaUUID;
            inValue.Body.psRFCEmisor = psRFCEmisor;
            inValue.Body.psRFCReceptor = psRFCReceptor;
            inValue.Body.sListaTotales = sListaTotales;
            inValue.Body.signature = signature;
            inValue.Body.sNombre = sNombre;
            inValue.Body.sContrasena = sContrasena;
            PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLResponse retVal = ((PAXConectorCapacitacion06.wsCancela.wcfCancelaASMXSoap)(this)).fnCancelarDistribuidoresXML(inValue);
            return retVal.Body.fnCancelarDistribuidoresXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PAXConectorCapacitacion06.wsCancela.fnCancelarXMLMPResponse PAXConectorCapacitacion06.wsCancela.wcfCancelaASMXSoap.fnCancelarXMLMP(PAXConectorCapacitacion06.wsCancela.fnCancelarXMLMPRequest request) {
            return base.Channel.fnCancelarXMLMP(request);
        }
        
        public string fnCancelarXMLMP(PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaUUID, string psRFCEmisor, string sNombre, string sContrasena) {
            PAXConectorCapacitacion06.wsCancela.fnCancelarXMLMPRequest inValue = new PAXConectorCapacitacion06.wsCancela.fnCancelarXMLMPRequest();
            inValue.Body = new PAXConectorCapacitacion06.wsCancela.fnCancelarXMLMPRequestBody();
            inValue.Body.sListaUUID = sListaUUID;
            inValue.Body.psRFCEmisor = psRFCEmisor;
            inValue.Body.sNombre = sNombre;
            inValue.Body.sContrasena = sContrasena;
            PAXConectorCapacitacion06.wsCancela.fnCancelarXMLMPResponse retVal = ((PAXConectorCapacitacion06.wsCancela.wcfCancelaASMXSoap)(this)).fnCancelarXMLMP(inValue);
            return retVal.Body.fnCancelarXMLMPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLMPResponse PAXConectorCapacitacion06.wsCancela.wcfCancelaASMXSoap.fnCancelarDistribuidoresXMLMP(PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLMPRequest request) {
            return base.Channel.fnCancelarDistribuidoresXMLMP(request);
        }
        
        public string fnCancelarDistribuidoresXMLMP(PAXConectorCapacitacion06.wsCancela.ArrayOfString sListaUUID, string psRFCEmisor, string signature, string sNombre, string sContrasena) {
            PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLMPRequest inValue = new PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLMPRequest();
            inValue.Body = new PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLMPRequestBody();
            inValue.Body.sListaUUID = sListaUUID;
            inValue.Body.psRFCEmisor = psRFCEmisor;
            inValue.Body.signature = signature;
            inValue.Body.sNombre = sNombre;
            inValue.Body.sContrasena = sContrasena;
            PAXConectorCapacitacion06.wsCancela.fnCancelarDistribuidoresXMLMPResponse retVal = ((PAXConectorCapacitacion06.wsCancela.wcfCancelaASMXSoap)(this)).fnCancelarDistribuidoresXMLMP(inValue);
            return retVal.Body.fnCancelarDistribuidoresXMLMPResult;
        }
    }
}
