//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaxEntregaPendientes.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"pcOrwzxA591q2tKEdDirKTWkwtKt81CLlaK6HATblPKIvQ9005pl6lmTuQ1P5qH6kv1Swvk3cbUbNoZYpZG/1ck75VHGFHZwXX27SYuyNcxFrJXoNETXbvas+5G0613fk4YlahisQ6paKln2pNzLXeB3nGOa1oMWzwX74t0JKcGY1GaqWpPmHCmANPbJV6UQTbACzs4MDSw38+lx2GzBxL7eouyWOLhSRhpHo2+ItQGCUXJP23P+nBFMX63hj7NYJQ79rf6zZnPakax8OitrKdSU9PCepY+5ZDp8F71BTPMBZ7dWbhvtF+dQvYeh0Vgxr7sXvd2x6qHyinp0CkE6xvCbPsyT1fH7tTA5kmKPxnL//NtlQcCscNS1qQ8VDlm9")]
        public string Conexion {
            get {
                return ((string)(this["Conexion"]));
            }
            set {
                this["Conexion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Entrega de Pendientes\\Pendientes\\")]
        public string RutaPendientes {
            get {
                return ((string)(this["RutaPendientes"]));
            }
            set {
                this["RutaPendientes"] = value;
            }
        }
    }
}
