//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneradorPruebasSantander.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneradorPruebasSantander.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a POVH580317B65,BBB010101HH1.
        /// </summary>
        internal static string RFCInexsistente {
            get {
                return ResourceManager.GetString("RFCInexsistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AA080808HL8,AAAL440727T22.
        /// </summary>
        internal static string RFCListaNegra {
            get {
                return ResourceManager.GetString("RFCListaNegra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 01|3.3|0|P|0||XXX|$FECHA$|
        ///02|||
        ///03|IHI980420SQ8|BANCO SANTANDER MEXICO SA INSTITUCION DE BANCA MULTLIPE, GRUPO SANTANDER|601|
        ///04|$RFC$|COMISION FEDERAL DE ELECTRICIDAD|P01|11022|0007944511|||
        ///05|0|0|Pago|ACT|84111506|1|
        ///06|00000000-0000-0000-0000-000000000000|1.0|1417217|2023802.75|MXN||03|2020-07-15T00:00:00|||0000011022|MAG041126GT8|0000000257|||||
        ///07|00000000-0000-0000-0000-000000000000|1417217|0310860000|MXN||PPD|1|3990595.02|2023802.75|1966792.27|
        ///06|00000000-0000-0000-0000-000000000000|1.0|141 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string sRegistro {
            get {
                return ResourceManager.GetString("sRegistro", resourceCulture);
            }
        }
    }
}
